# Generated by Django 3.0.5 on 2020-05-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=70)),
                ('Author', models.CharField(max_length=50)),
                ('Add_Book', models.FileField(upload_to='pdf/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=20)),
                ('cover_page', models.ImageField(upload_to='imaages/')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
