# Generated by Django 3.0.5 on 2020-05-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
